sudo: required
language: c
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["gcc-8"]
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang
script:
  - "bin/travis-install"
before_install:
  - eval "${MATRIX_EVAL}"