sudo: required
language: c
compiler:
 - clang
 - gcc
arch:
 packages:
  - cmake
  # `clang` owns `clang-tidy`
  - clang
 script:
  - ".travis/install"
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"