after_build:
  - ctest -j$NUMBER_OF_PROCESSORS
before_build:
  - cmake -G "Visual Studio 14 2015 Win64" .
build:
  parallel: true
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
configuration:
  - Debug
  - Release
image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019
platform:
  - x64