after_build:
  - make test
before_build:
  - cmake -G "Visual Studio 14 2015 Win64" .
build:
 parallel: true
configuration:
  - Debug
  - Release
image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019
platform:
  - x64