image:
 - Visual Studio 2015
 - Visual Studio 2017
configuration:
 - Release
 - Debug
platform:
 - x64
before_build:
 - if %PLATFORM% == x64 (set GENERATOR="Visual Studio 14 2015 Win64")
 - mkdir build
 - cd build
 - cmake -G %GENERATOR% ..
build:
 parallel: true