image:
 - Visual Studio 2013
 - Visual Studio 2015
 - Visual Studio 2017
configuration:
 - Release
 - Debug
platform:
 - x64
before_build:
 - cmd: |
    mkdir build
    cd build
    cmake --version
    cmake ..