jobs:
  unix-like:
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Fetch history for all tags
      run: .github/workflows/fetch-tags
    - name: Build targets
      run: .github/workflows/build ${{ matrix.build-type }} ${{ matrix.compiler }}
    - name: Run tests
      run: .github/workflows/test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        compiler:
          - clang
          - gcc
        build-type:
          - Debug
          - Release
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch history for all tags
      run: .github/workflows/fetch-tags
      shell: bash
    - name: Build targets
      run: .github/workflows/build ${{ matrix.build-type }}
      shell: bash
    - name: Run tests
      run: .github/workflows/test
      shell: bash
    strategy:
      matrix:
        build-type:
          - Debug
          - Release
name: build
on: push