jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Fetch history for all tags
      run: |
        git fetch --depth=1 origin "+refs/tags/*:refs/tags/*"
        git fetch --prune --unshallow
    - name: Build targets
      run: .github/workflows/main.sh ${{ matrix.os }} ${{ matrix.build-type }} ${{ matrix.cc }}
      shell: bash
    - name: Run tests
      run: cd build && CTEST_OUTPUT_ON_FAILURE=1 ctest -j$(nproc)
      shell: bash
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        cc:
          - clang
          - gcc
        build-type:
          - Debug
          - Release
name: build
on: push